@extends('layouts.default')

@session('content')

	<div class="container">
		<h1>lakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjalslakdfjlkajdsfklajsfkljadklfjals</h1>
	</div>

@stop